global:
    slack_api_url: "https://hooks.slack.com/services/XXXXXXXXXXXXXXX"

route:
    receiver: "default"
    routes:
        - match:
              severity: warning
          receiver: slack

        - match:
              severity: critical
          receiver: email
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 5m

receivers:
    - name: default
      email_configs:
          - to: "to@youremail.com"
            from: "default-alerts@yourdomain.com"
            smarthost: "smtp.host.com:2525"
            auth_username: "smtpusername"
            auth_password: "smtppassword"
            html: '{{ template "email" .}}'

    - name: slack
      slack_configs:
          - send_resolved: true
            username: '{{ template "slack.default.username" . }}'
            color: '{{ if eq .Status "firing" }}good{{ else }}good{{ end }}'
            title: '{{ template "slack.default.title" . }}'
            title_link: '{{ template "slack.default.titlelink" . }}'
            pretext: "{{ .CommonAnnotations.summary }}"
            text: >-
                {{ range .Alerts }}
                 *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`📊
                 *Description:* {{ .Annotations.description }}
                 *Details:*
                 {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                 {{ end }}
                {{ end }}

    - name: email
      email_configs:
          - to: "to@youremail.com"
            from: "default-alerts@yourdomain.com"
            smarthost: "smtp.host.com:2525"
            auth_username: "smtpusername"
            auth_password: "smtppassword"
            html: '{{ template "email" .}}'

templates:
    - "~/prometheus/alert.tmpl"
