alerting:
    alertmanagers:
        - static_configs:
            - tartgets:
                - 'alertmanager:9093'

rule_files:
    - "alert.rules"

global:
    scrape_interval: 5s
    external_labels:
        cluster: prod2

scrape_configs:
    - job_name: "prometheus_master"
      scrape_interval: 5s
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "node_exporter_centos"
      scrape_interval: 5s
      static_configs:
          - targets: ["node-exporter:9100"]

    - job_name: "nginx_exporter"
      scrape_interval: 5s
      static_configs:
          - targets: ["nginx-exporter:9113"]

    - job_name: "php-fpm-exporter"
      scrape_interval: 5s
      static_configs:
          - targets: ["php-fpm-exporter:9253"]

    - job_name: "my-sql-exporter"
      scrape_interval: 5s
      static_configs:
          - targets: ["mysql-exporter:9104"]

    - job_name: "blackbox-tcp"
      scrape_interval: 5s
      metrics_path: /probe
      params:
          module: [tcp_connect]
      static_configs:
          - targets: ["myadmin:80"] #Проверяю работу CMS
      relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox-exporter:9115
