version: "3"

volumes:
    prometheus1_data: {}
    prometheus2_data: {}
    prometheus3_data: {}
    prometheus4_data: {}
    grafana_data: {}
    minio_data: {}

services:
    prometheus-1:
        image: prom/prometheus:v2.52.0
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus1_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus1.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.max-block-duration=30m"
            - "--storage.tsdb.min-block-duration=30m"
            - "--web.enable-lifecycle"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
        ports:
            - 9081:9090
        networks:
            - docker-nginx-php-mysql_default

    prometheus-2:
        image: prom/prometheus:v2.52.0
        volumes:
            - ./prometheus/:/etc/prometheus/
            - prometheus2_data:/prometheus
        command:
            - "--config.file=/etc/prometheus/prometheus2.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.max-block-duration=30m"
            - "--storage.tsdb.min-block-duration=30m"
            - "--web.enable-lifecycle"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
        ports:
            - 9082:9090
        networks:
            - docker-nginx-php-mysql_default

    thanos-sidecar-1:
        image: quay.io/thanos/thanos:v0.31.0
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus1_data:/prometheus
        command:
            - "sidecar"
            - "--tsdb.path=/prometheus"
            - "--prometheus.url=http://prometheus-1:9090"
            - "--grpc-address=0.0.0.0:10091"
            - "--http-address=0.0.0.0:10902"
            - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
        depends_on:
            - prometheus-1
            - minio
        networks:
            - docker-nginx-php-mysql_default

    thanos-sidecar-2:
        image: quay.io/thanos/thanos:v0.31.0
        volumes:
            - ./thanos/:/etc/thanos/
            - prometheus2_data:/prometheus
        command:
            - "sidecar"
            - "--tsdb.path=/prometheus"
            - "--prometheus.url=http://prometheus-2:9090"
            - "--grpc-address=0.0.0.0:10091"
            - "--http-address=0.0.0.0:10902"
            - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
        depends_on:
            - prometheus-2
            - minio
        networks:
            - docker-nginx-php-mysql_default

    thanos-query-frontend:
        image: quay.io/thanos/thanos:v0.31.0
        command:
            - "query-frontend"
            - "--http-address=0.0.0.0:10901"
            - "--query-frontend.downstream-url=http://thanos-querier:10902"
        ports:
            - 10901:10901
        depends_on:
            - thanos-querier
        networks:
            - docker-nginx-php-mysql_default

    thanos-querier:
        image: quay.io/thanos/thanos:v0.31.0
        command:
            - "query"
            - "--grpc-address=0.0.0.0:10091"
            - "--http-address=0.0.0.0:10902"
            - "--query.replica-label=replica"
            - "--store=thanos-sidecar-1:10091"
            - "--store=thanos-sidecar-2:10091"
            - "--store=thanos-store-gateway:10091"
            - "--store=thanos-ruler:10091"
        ports:
            - 10902:10902
        depends_on:
            - thanos-sidecar-1
            - thanos-sidecar-2
        networks:
            - docker-nginx-php-mysql_default

    thanos-store-gateway:
        image: quay.io/thanos/thanos:v0.31.0
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - "store"
            - "--grpc-address=0.0.0.0:10091"
            - "--http-address=0.0.0.0:10902"
            - "--data-dir=/tmp/thanos/store"
            - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
        depends_on:
            - minio
        networks:
            - docker-nginx-php-mysql_default

    thanos-compactor:
        image: quay.io/thanos/thanos:v0.31.0
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - "compact"
            - "--log.level=debug"
            - "--data-dir=/data"
            - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
            - "--wait"
            - "--retention.resolution-raw=15d"
            - "--retention.resolution-5m=15d"
            - "--retention.resolution-1h=15d"
        depends_on:
            - minio
        networks:
            - docker-nginx-php-mysql_default

    thanos-ruler:
        image: quay.io/thanos/thanos:v0.31.0
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - "rule"
            - "--grpc-address=0.0.0.0:10091"
            - "--http-address=0.0.0.0:10902"
            - "--log.level=debug"
            - "--data-dir=/data"
            - "--eval-interval=15s"
            - "--rule-file=/etc/thanos/*.rules.yaml"
            - "--alertmanagers.url=http://alertmanager:9093"
            - "--query=thanos-querier:10902"
            - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
            - '--label=ruler_cluster="vegas"'
            - '--label=ruler_replica="r1"'
        ports:
            - 10903:10902
        depends_on:
            - minio
            - thanos-querier
        networks:
            - docker-nginx-php-mysql_default

    thanos-bucket-web:
        image: quay.io/thanos/thanos:v0.31.0
        volumes:
            - ./thanos/:/etc/thanos/
        command:
            - "tools"
            - "bucket"
            - "web"
            - "--http-address=0.0.0.0:10902"
            - "--log.level=debug"
            - "--objstore.config-file=/etc/thanos/bucket_config.yaml"
            - "--refresh=5m"
            - "--timeout=2m"
            - "--label=replica"
        ports:
            - 10904:10902
        depends_on:
            - minio
        networks:
            - docker-nginx-php-mysql_default

    minio:
        image: minio/minio:RELEASE.2020-05-01T22-19-14Z
        volumes:
            - minio_data:/data
        entrypoint: sh
        command: -c 'mkdir -p /data/demo-bucket && /usr/bin/minio server /data'
        environment:
            - MINIO_ACCESS_KEY=adminadmin
            - MINIO_SECRET_KEY=adminadmin
            - MINIO_PROMETHEUS_AUTH_TYPE=public
        ports:
            - 9000:9000
        networks:
            - docker-nginx-php-mysql_default

networks:
    docker-nginx-php-mysql_default:
        external: true
